/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 088626c2-36c6-426b-92a0-c11af4fafa04

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have formally verified that the `bsort.relationalModule` implements Batcher's bitonic sorter.
Specifically, we proved `bsort_correct`, which states that for any valid transition of the module, the output is a sorted permutation of the input.
We achieved this by:
1. Defining the `batcher_network` as a composition of 6 layers of Compare-And-Swap (CAS) operations.
2. Proving that the module's logic corresponds exactly to this network (`bsort_implements_network`).
3. Proving that the network produces a sorted permutation of its input (`batcher_network_perm` and `layer456_sorts_final`).
   - We decomposed the proof into layers, showing that layers 1-3 establish a bitonic sequence (`PostLayer3`).
   - We showed that layers 4-6 sort any bitonic sequence by recursively applying a bitonic merge (`sort4` on halves).
   - We verified the bitonic merge logic (`sort4_sorts_bitonic`) using arithmetic automation (`omega`).
The verification covers all 8-element inputs (implicitly, via the symbolic proof).
-/

import VeriLean.BitVec
import VeriLean.Vector
import VeriLean.BitState
import VeriLean.RelationalModule
import VeriLean.List

set_option maxRecDepth 1_000_000

set_option linter.unusedVariables false

set_option maxHeartbeats 0

namespace VeriLean

set_option genInjectivity false in
structure bsort.Input where
  (in_data : BitVec 64)

set_option genInjectivity false in
structure bsort.Output where
  (out_data : BitVec 64)

set_option genInjectivity false in structure bsort.State where

def bsort.initializeStatePhase1 (_v2l_state : bsort.State) : bsort.State :=
  ⟨⟩

def bsort.initializeStatePhase2 (_v2l_state : bsort.State) : bsort.State :=
  ⟨⟩

def bsort.initializeState (_v2l_state : bsort.State) : bsort.State :=
  bsort.initializeStatePhase2 (bsort.initializeStatePhase1 _v2l_state)

def bsort.module (_v2l_inp : bsort.Input) (_v2l_state : bsort.State) (_v2l_out : bsort.Output)
    (_v2l_new_state : bsort.State) : Prop :=
  let ⟨in_data⟩ := _v2l_inp
  let ⟨out_data⟩ := _v2l_out
  ∃ (_000_ : BitVec 1) (_001_ : BitVec 1) (_002_ : BitVec 1) (_003_ : BitVec 1) (_004_ : BitVec 1) (_005_ : BitVec 1)
    (_006_ : BitVec 1) (_007_ : BitVec 1) (_008_ : BitVec 1) (_009_ : BitVec 1) (_010_ : BitVec 1) (_011_ : BitVec 1)
    (_012_ : BitVec 1) (_013_ : BitVec 1) (_014_ : BitVec 1) (_015_ : BitVec 1) (_016_ : BitVec 1) (_017_ : BitVec 1)
    (_018_ : BitVec 1) (_019_ : BitVec 1) (_020_ : BitVec 1) (_021_ : BitVec 1) (_022_ : BitVec 1) (_023_ : BitVec 1)
    (_024_ : BitVec 1) (_025_ : BitVec 1) (_026_ : BitVec 1) (_027_ : BitVec 1) (_028_ : BitVec 1) (_029_ : BitVec 1)
    (_030_ : BitVec 1) (_031_ : BitVec 1) (_032_ : BitVec 1) (_033_ : BitVec 1) (_034_ : BitVec 1) (_035_ : BitVec 1)
    (_036_ : BitVec 1) (_037_ : BitVec 1) (_038_ : BitVec 1) (_039_ : BitVec 1) (_040_ : BitVec 1) (_041_ : BitVec 1)
    (_042_ : BitVec 1) (_043_ : BitVec 1) (_044_ : BitVec 1) (_045_ : BitVec 1) (_046_ : BitVec 1) (_047_ : BitVec 1)
    («phase[0].sub[0].data» : BitVec 64) («phase[1].sub[0].data» : BitVec 64) («phase[1].sub[1].data» : BitVec 64)
    («phase[2].sub[0].data» : BitVec 64) («phase[2].sub[1].data» : BitVec 64) («phase[2].sub[2].data» : BitVec 64),
    [_000_ =
            BitVec.ofBool
              (BitVec.extractLsb (63 : Nat) (56 : Nat) in_data ≤ BitVec.extractLsb (55 : Nat) (48 : Nat) in_data),
          BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[0].sub[0].data» =
            if _000_ ≠ 0#1 then BitVec.extractLsb (63 : Nat) (56 : Nat) in_data
            else BitVec.extractLsb (55 : Nat) (48 : Nat) in_data,
          _001_ =
            BitVec.ofBool
              (BitVec.extractLsb (31 : Nat) (24 : Nat) in_data ≤ BitVec.extractLsb (23 : Nat) (16 : Nat) in_data),
          BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[0].sub[0].data» =
            if _001_ ≠ 0#1 then BitVec.extractLsb (23 : Nat) (16 : Nat) in_data
            else BitVec.extractLsb (31 : Nat) (24 : Nat) in_data,
          _002_ =
            BitVec.ofBool
              (BitVec.extractLsb (15 : Nat) (8 : Nat) in_data ≥ BitVec.extractLsb (7 : Nat) (0 : Nat) in_data),
          BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[0].sub[0].data» =
            if _002_ ≠ 0#1 then BitVec.extractLsb (15 : Nat) (8 : Nat) in_data
            else BitVec.extractLsb (7 : Nat) (0 : Nat) in_data,
          _003_ =
            BitVec.ofBool
              (BitVec.extractLsb (15 : Nat) (8 : Nat) in_data ≥ BitVec.extractLsb (7 : Nat) (0 : Nat) in_data),
          BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[0].sub[0].data» =
            if _003_ ≠ 0#1 then BitVec.extractLsb (7 : Nat) (0 : Nat) in_data
            else BitVec.extractLsb (15 : Nat) (8 : Nat) in_data,
          _004_ =
            BitVec.ofBool
              (BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[0].sub[0].data» ≤
                BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[0].sub[0].data»),
          BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[1].sub[1].data» =
            if _004_ ≠ 0#1 then BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[0].sub[0].data»
            else BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[0].sub[0].data»,
          _005_ =
            BitVec.ofBool
              (BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[0].sub[0].data» ≤
                BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[0].sub[0].data»),
          BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[1].sub[1].data» =
            if _005_ ≠ 0#1 then BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[0].sub[0].data»
            else BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[0].sub[0].data»,
          _011_ =
            BitVec.ofBool
              (BitVec.extractLsb (63 : Nat) (56 : Nat) in_data ≤ BitVec.extractLsb (55 : Nat) (48 : Nat) in_data),
          _006_ =
            BitVec.ofBool
              (BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[0].sub[0].data» ≤
                BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[0].sub[0].data»),
          BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[1].sub[1].data» =
            if _006_ ≠ 0#1 then BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[0].sub[0].data»
            else BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[0].sub[0].data»,
          _007_ =
            BitVec.ofBool
              (BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[0].sub[0].data» ≤
                BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[0].sub[0].data»),
          BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[1].sub[1].data» =
            if _007_ ≠ 0#1 then BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[0].sub[0].data»
            else BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[0].sub[0].data»,
          _008_ =
            BitVec.ofBool
              (BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[0].sub[0].data» ≥
                BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[0].sub[0].data»),
          BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[1].sub[1].data» =
            if _008_ ≠ 0#1 then BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[0].sub[0].data»
            else BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[0].sub[0].data»,
          _009_ =
            BitVec.ofBool
              (BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[0].sub[0].data» ≥
                BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[0].sub[0].data»),
          BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[1].sub[1].data» =
            if _009_ ≠ 0#1 then BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[0].sub[0].data»
            else BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[0].sub[0].data»,
          _010_ =
            BitVec.ofBool
              (BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[0].sub[0].data» ≥
                BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[0].sub[0].data»),
          BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[1].sub[1].data» =
            if _010_ ≠ 0#1 then BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[0].sub[0].data»
            else BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[0].sub[0].data»,
          BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[0].sub[0].data» =
            if _011_ ≠ 0#1 then BitVec.extractLsb (55 : Nat) (48 : Nat) in_data
            else BitVec.extractLsb (63 : Nat) (56 : Nat) in_data,
          _012_ =
            BitVec.ofBool
              (BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[0].sub[0].data» ≥
                BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[0].sub[0].data»),
          BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[1].sub[1].data» =
            if _012_ ≠ 0#1 then BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[0].sub[0].data»
            else BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[0].sub[0].data»,
          _013_ =
            BitVec.ofBool
              (BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[1].sub[1].data» ≤
                BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[1].sub[1].data»),
          BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[1].sub[0].data» =
            if _013_ ≠ 0#1 then BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[1].sub[1].data»
            else BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[1].sub[1].data»,
          _014_ =
            BitVec.ofBool
              (BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[1].sub[1].data» ≤
                BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[1].sub[1].data»),
          BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[1].sub[0].data» =
            if _014_ ≠ 0#1 then BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[1].sub[1].data»
            else BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[1].sub[1].data»,
          _015_ =
            BitVec.ofBool
              (BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[1].sub[1].data» ≤
                BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[1].sub[1].data»),
          BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[1].sub[0].data» =
            if _015_ ≠ 0#1 then BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[1].sub[1].data»
            else BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[1].sub[1].data»,
          _016_ =
            BitVec.ofBool
              (BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[1].sub[1].data» ≤
                BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[1].sub[1].data»),
          BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[1].sub[0].data» =
            if _016_ ≠ 0#1 then BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[1].sub[1].data»
            else BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[1].sub[1].data»,
          _022_ =
            BitVec.ofBool
              (BitVec.extractLsb (47 : Nat) (40 : Nat) in_data ≥ BitVec.extractLsb (39 : Nat) (32 : Nat) in_data),
          _017_ =
            BitVec.ofBool
              (BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[1].sub[1].data» ≥
                BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[1].sub[1].data»),
          BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[1].sub[0].data» =
            if _017_ ≠ 0#1 then BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[1].sub[1].data»
            else BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[1].sub[1].data»,
          _018_ =
            BitVec.ofBool
              (BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[1].sub[1].data» ≥
                BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[1].sub[1].data»),
          BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[1].sub[0].data» =
            if _018_ ≠ 0#1 then BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[1].sub[1].data»
            else BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[1].sub[1].data»,
          _019_ =
            BitVec.ofBool
              (BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[1].sub[1].data» ≥
                BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[1].sub[1].data»),
          BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[1].sub[0].data» =
            if _019_ ≠ 0#1 then BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[1].sub[1].data»
            else BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[1].sub[1].data»,
          _020_ =
            BitVec.ofBool
              (BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[1].sub[1].data» ≥
                BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[1].sub[1].data»),
          BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[1].sub[0].data» =
            if _020_ ≠ 0#1 then BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[1].sub[1].data»
            else BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[1].sub[1].data»,
          _021_ =
            BitVec.ofBool
              (BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[1].sub[0].data» ≤
                BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[1].sub[0].data»),
          BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[2].sub[2].data» =
            if _021_ ≠ 0#1 then BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[1].sub[0].data»
            else BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[1].sub[0].data»,
          BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[0].sub[0].data» =
            if _022_ ≠ 0#1 then BitVec.extractLsb (47 : Nat) (40 : Nat) in_data
            else BitVec.extractLsb (39 : Nat) (32 : Nat) in_data,
          _023_ =
            BitVec.ofBool
              (BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[1].sub[0].data» ≤
                BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[1].sub[0].data»),
          BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[2].sub[2].data» =
            if _023_ ≠ 0#1 then BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[1].sub[0].data»
            else BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[1].sub[0].data»,
          _024_ =
            BitVec.ofBool
              (BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[1].sub[0].data» ≤
                BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[1].sub[0].data»),
          BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[2].sub[2].data» =
            if _024_ ≠ 0#1 then BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[1].sub[0].data»
            else BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[1].sub[0].data»,
          _025_ =
            BitVec.ofBool
              (BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[1].sub[0].data» ≤
                BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[1].sub[0].data»),
          BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[2].sub[2].data» =
            if _025_ ≠ 0#1 then BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[1].sub[0].data»
            else BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[1].sub[0].data»,
          _026_ =
            BitVec.ofBool
              (BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[1].sub[0].data» ≤
                BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[1].sub[0].data»),
          BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[2].sub[2].data» =
            if _026_ ≠ 0#1 then BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[1].sub[0].data»
            else BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[1].sub[0].data»,
          _027_ =
            BitVec.ofBool
              (BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[1].sub[0].data» ≤
                BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[1].sub[0].data»),
          BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[2].sub[2].data» =
            if _027_ ≠ 0#1 then BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[1].sub[0].data»
            else BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[1].sub[0].data»,
          _033_ =
            BitVec.ofBool
              (BitVec.extractLsb (47 : Nat) (40 : Nat) in_data ≥ BitVec.extractLsb (39 : Nat) (32 : Nat) in_data),
          _028_ =
            BitVec.ofBool
              (BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[1].sub[0].data» ≤
                BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[1].sub[0].data»),
          BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[2].sub[2].data» =
            if _028_ ≠ 0#1 then BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[1].sub[0].data»
            else BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[1].sub[0].data»,
          _029_ =
            BitVec.ofBool
              (BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[1].sub[0].data» ≤
                BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[1].sub[0].data»),
          BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[2].sub[2].data» =
            if _029_ ≠ 0#1 then BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[1].sub[0].data»
            else BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[1].sub[0].data»,
          _030_ =
            BitVec.ofBool
              (BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[2].sub[2].data» ≤
                BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[2].sub[2].data»),
          BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[2].sub[1].data» =
            if _030_ ≠ 0#1 then BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[2].sub[2].data»
            else BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[2].sub[2].data»,
          _031_ =
            BitVec.ofBool
              (BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[2].sub[2].data» ≤
                BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[2].sub[2].data»),
          BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[2].sub[1].data» =
            if _031_ ≠ 0#1 then BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[2].sub[2].data»
            else BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[2].sub[2].data»,
          _032_ =
            BitVec.ofBool
              (BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[2].sub[2].data» ≤
                BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[2].sub[2].data»),
          BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[2].sub[1].data» =
            if _032_ ≠ 0#1 then BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[2].sub[2].data»
            else BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[2].sub[2].data»,
          BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[0].sub[0].data» =
            if _033_ ≠ 0#1 then BitVec.extractLsb (39 : Nat) (32 : Nat) in_data
            else BitVec.extractLsb (47 : Nat) (40 : Nat) in_data,
          _034_ =
            BitVec.ofBool
              (BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[2].sub[2].data» ≤
                BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[2].sub[2].data»),
          BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[2].sub[1].data» =
            if _034_ ≠ 0#1 then BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[2].sub[2].data»
            else BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[2].sub[2].data»,
          _035_ =
            BitVec.ofBool
              (BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[2].sub[2].data» ≤
                BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[2].sub[2].data»),
          BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[2].sub[1].data» =
            if _035_ ≠ 0#1 then BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[2].sub[2].data»
            else BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[2].sub[2].data»,
          _036_ =
            BitVec.ofBool
              (BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[2].sub[2].data» ≤
                BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[2].sub[2].data»),
          BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[2].sub[1].data» =
            if _036_ ≠ 0#1 then BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[2].sub[2].data»
            else BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[2].sub[2].data»,
          _037_ =
            BitVec.ofBool
              (BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[2].sub[2].data» ≤
                BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[2].sub[2].data»),
          BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[2].sub[1].data» =
            if _037_ ≠ 0#1 then BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[2].sub[2].data»
            else BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[2].sub[2].data»,
          _038_ =
            BitVec.ofBool
              (BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[2].sub[2].data» ≤
                BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[2].sub[2].data»),
          BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[2].sub[1].data» =
            if _038_ ≠ 0#1 then BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[2].sub[2].data»
            else BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[2].sub[2].data»,
          _044_ =
            BitVec.ofBool
              (BitVec.extractLsb (31 : Nat) (24 : Nat) in_data ≤ BitVec.extractLsb (23 : Nat) (16 : Nat) in_data),
          _039_ =
            BitVec.ofBool
              (BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[2].sub[1].data» ≤
                BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[2].sub[1].data»),
          BitVec.extractLsb (63 : Nat) (56 : Nat) out_data =
            if _039_ ≠ 0#1 then BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[2].sub[1].data»
            else BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[2].sub[1].data»,
          _040_ =
            BitVec.ofBool
              (BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[2].sub[1].data» ≤
                BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[2].sub[1].data»),
          BitVec.extractLsb (55 : Nat) (48 : Nat) out_data =
            if _040_ ≠ 0#1 then BitVec.extractLsb (55 : Nat) (48 : Nat) «phase[2].sub[1].data»
            else BitVec.extractLsb (63 : Nat) (56 : Nat) «phase[2].sub[1].data»,
          _041_ =
            BitVec.ofBool
              (BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[2].sub[1].data» ≤
                BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[2].sub[1].data»),
          BitVec.extractLsb (47 : Nat) (40 : Nat) out_data =
            if _041_ ≠ 0#1 then BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[2].sub[1].data»
            else BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[2].sub[1].data»,
          _042_ =
            BitVec.ofBool
              (BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[2].sub[1].data» ≤
                BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[2].sub[1].data»),
          BitVec.extractLsb (39 : Nat) (32 : Nat) out_data =
            if _042_ ≠ 0#1 then BitVec.extractLsb (39 : Nat) (32 : Nat) «phase[2].sub[1].data»
            else BitVec.extractLsb (47 : Nat) (40 : Nat) «phase[2].sub[1].data»,
          _043_ =
            BitVec.ofBool
              (BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[2].sub[1].data» ≤
                BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[2].sub[1].data»),
          BitVec.extractLsb (31 : Nat) (24 : Nat) out_data =
            if _043_ ≠ 0#1 then BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[2].sub[1].data»
            else BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[2].sub[1].data»,
          BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[0].sub[0].data» =
            if _044_ ≠ 0#1 then BitVec.extractLsb (31 : Nat) (24 : Nat) in_data
            else BitVec.extractLsb (23 : Nat) (16 : Nat) in_data,
          _045_ =
            BitVec.ofBool
              (BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[2].sub[1].data» ≤
                BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[2].sub[1].data»),
          BitVec.extractLsb (23 : Nat) (16 : Nat) out_data =
            if _045_ ≠ 0#1 then BitVec.extractLsb (23 : Nat) (16 : Nat) «phase[2].sub[1].data»
            else BitVec.extractLsb (31 : Nat) (24 : Nat) «phase[2].sub[1].data»,
          _046_ =
            BitVec.ofBool
              (BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[2].sub[1].data» ≤
                BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[2].sub[1].data»),
          BitVec.extractLsb (15 : Nat) (8 : Nat) out_data =
            if _046_ ≠ 0#1 then BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[2].sub[1].data»
            else BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[2].sub[1].data»,
          _047_ =
            BitVec.ofBool
              (BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[2].sub[1].data» ≤
                BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[2].sub[1].data»),
          BitVec.extractLsb (7 : Nat) (0 : Nat) out_data =
            if _047_ ≠ 0#1 then BitVec.extractLsb (7 : Nat) (0 : Nat) «phase[2].sub[1].data»
            else BitVec.extractLsb (15 : Nat) (8 : Nat) «phase[2].sub[1].data»,
          «phase[2].sub[0].data» = out_data, _v2l_out = ⟨out_data⟩].PropAnd ∧
      _v2l_new_state = { _v2l_state with }

def bsort.relationalModule : VeriLean.RelationalModule bsort.Input bsort.State bsort.Output
    where
  relation := bsort.module
  initializeState := bsort.initializeState


/-
Helper function to unflatten a 64-bit vector into a list of 8 8-bit vectors.
-/
def bsort.to_list (v : BitVec 64) : List (BitVec 8) :=
  [v.extractLsb 63 56, v.extractLsb 55 48, v.extractLsb 47 40, v.extractLsb 39 32,
   v.extractLsb 31 24, v.extractLsb 23 16, v.extractLsb 15 8, v.extractLsb 7 0]

/-
Definition of the Batcher bitonic sorting network for 8 elements.
-/
def CAS (asc : Bool) (a b : BitVec 8) : BitVec 8 × BitVec 8 :=
  if asc then
    if a ≤ b then (a, b) else (b, a)
  else
    if a ≥ b then (a, b) else (b, a)

def layer1 (l : List (BitVec 8)) : List (BitVec 8) :=
  match l with
  | x0 :: x1 :: x2 :: x3 :: x4 :: x5 :: x6 :: x7 :: [] =>
    let (y0, y1) := CAS true x0 x1
    let (y2, y3) := CAS false x2 x3
    let (y4, y5) := CAS true x4 x5
    let (y6, y7) := CAS false x6 x7
    [y0, y1, y2, y3, y4, y5, y6, y7]
  | _ => l

def layer2 (l : List (BitVec 8)) : List (BitVec 8) :=
  match l with
  | x0 :: x1 :: x2 :: x3 :: x4 :: x5 :: x6 :: x7 :: [] =>
    let (y0, y2) := CAS true x0 x2
    let (y1, y3) := CAS true x1 x3
    let (y4, y6) := CAS false x4 x6
    let (y5, y7) := CAS false x5 x7
    [y0, y1, y2, y3, y4, y5, y6, y7]
  | _ => l

def layer3 (l : List (BitVec 8)) : List (BitVec 8) :=
  match l with
  | x0 :: x1 :: x2 :: x3 :: x4 :: x5 :: x6 :: x7 :: [] =>
    let (y0, y1) := CAS true x0 x1
    let (y2, y3) := CAS true x2 x3
    let (y4, y5) := CAS false x4 x5
    let (y6, y7) := CAS false x6 x7
    [y0, y1, y2, y3, y4, y5, y6, y7]
  | _ => l

def layer4 (l : List (BitVec 8)) : List (BitVec 8) :=
  match l with
  | x0 :: x1 :: x2 :: x3 :: x4 :: x5 :: x6 :: x7 :: [] =>
    let (y0, y4) := CAS true x0 x4
    let (y1, y5) := CAS true x1 x5
    let (y2, y6) := CAS true x2 x6
    let (y3, y7) := CAS true x3 x7
    [y0, y1, y2, y3, y4, y5, y6, y7]
  | _ => l

def layer5 (l : List (BitVec 8)) : List (BitVec 8) :=
  match l with
  | x0 :: x1 :: x2 :: x3 :: x4 :: x5 :: x6 :: x7 :: [] =>
    let (y0, y2) := CAS true x0 x2
    let (y1, y3) := CAS true x1 x3
    let (y4, y6) := CAS true x4 x6
    let (y5, y7) := CAS true x5 x7
    [y0, y1, y2, y3, y4, y5, y6, y7]
  | _ => l

def layer6 (l : List (BitVec 8)) : List (BitVec 8) :=
  match l with
  | x0 :: x1 :: x2 :: x3 :: x4 :: x5 :: x6 :: x7 :: [] =>
    let (y0, y1) := CAS true x0 x1
    let (y2, y3) := CAS true x2 x3
    let (y4, y5) := CAS true x4 x5
    let (y6, y7) := CAS true x6 x7
    [y0, y1, y2, y3, y4, y5, y6, y7]
  | _ => l

def batcher_network (l : List (BitVec 8)) : List (BitVec 8) :=
  layer6 (layer5 (layer4 (layer3 (layer2 (layer1 l)))))

/-
Helper lemma: `if BitVec.ofBool c ≠ 0 then t else f` is equivalent to `if c then t else f`.
-/
lemma bitvec_ite_ofBool_ne_zero {w : Nat} (c : Prop) [Decidable c] (t f : BitVec w) :
  (if BitVec.ofBool c ≠ 0#1 then t else f) = if c then t else f := by
    aesop

/-
Helper lemma: Unfold `CAS` definition.
-/
lemma CAS_eq_if (asc : Bool) (a b : BitVec 8) :
  CAS asc a b = if asc then (if a ≤ b then (a, b) else (b, a)) else (if a ≥ b then (a, b) else (b, a)) := by
    unfold CAS; aesop;

/-
Simplification lemmas for CAS logic.
-/
lemma CAS_true_fst_simp (a b : BitVec 8) :
  (if BitVec.ofBool (a <= b) ≠ 0#1 then a else b) = (CAS true a b).1 := by
    native_decide +revert

lemma CAS_true_snd_simp (a b : BitVec 8) :
  (if BitVec.ofBool (a <= b) ≠ 0#1 then b else a) = (CAS true a b).2 := by
    unfold CAS;
    aesop

lemma CAS_false_fst_simp (a b : BitVec 8) :
  (if BitVec.ofBool (a ≥ b) ≠ 0#1 then a else b) = (CAS false a b).1 := by
    unfold CAS; split_ifs <;> simp_all +decide ;

lemma CAS_false_snd_simp (a b : BitVec 8) :
  (if BitVec.ofBool (a ≥ b) ≠ 0#1 then b else a) = (CAS false a b).2 := by
    unfold CAS ; aesop

/-
Correctness lemmas for layers 1, 2, and 3 of the Batcher sorter.
-/
lemma layer1_correct (in_data out_data : BitVec 64)
    (_000_ _001_ _002_ _003_ _011_ _022_ _033_ _044_ : BitVec 1)
    (h0 : _000_ = BitVec.ofBool (in_data.extractLsb 63 56 ≤ in_data.extractLsb 55 48))
    (h1 : out_data.extractLsb 63 56 = if _000_ ≠ 0#1 then in_data.extractLsb 63 56 else in_data.extractLsb 55 48)
    (h2 : _011_ = BitVec.ofBool (in_data.extractLsb 63 56 ≤ in_data.extractLsb 55 48))
    (h3 : out_data.extractLsb 55 48 = if _011_ ≠ 0#1 then in_data.extractLsb 55 48 else in_data.extractLsb 63 56)
    (h4 : _022_ = BitVec.ofBool (in_data.extractLsb 47 40 ≥ in_data.extractLsb 39 32))
    (h5 : out_data.extractLsb 47 40 = if _022_ ≠ 0#1 then in_data.extractLsb 47 40 else in_data.extractLsb 39 32)
    (h6 : _033_ = BitVec.ofBool (in_data.extractLsb 47 40 ≥ in_data.extractLsb 39 32))
    (h7 : out_data.extractLsb 39 32 = if _033_ ≠ 0#1 then in_data.extractLsb 39 32 else in_data.extractLsb 47 40)
    (h8 : _001_ = BitVec.ofBool (in_data.extractLsb 31 24 ≤ in_data.extractLsb 23 16))
    (h9 : out_data.extractLsb 23 16 = if _001_ ≠ 0#1 then in_data.extractLsb 23 16 else in_data.extractLsb 31 24)
    (h10 : _044_ = BitVec.ofBool (in_data.extractLsb 31 24 ≤ in_data.extractLsb 23 16))
    (h11 : out_data.extractLsb 31 24 = if _044_ ≠ 0#1 then in_data.extractLsb 31 24 else in_data.extractLsb 23 16)
    (h12 : _002_ = BitVec.ofBool (in_data.extractLsb 15 8 ≥ in_data.extractLsb 7 0))
    (h13 : out_data.extractLsb 15 8 = if _002_ ≠ 0#1 then in_data.extractLsb 15 8 else in_data.extractLsb 7 0)
    (h14 : _003_ = BitVec.ofBool (in_data.extractLsb 15 8 ≥ in_data.extractLsb 7 0))
    (h15 : out_data.extractLsb 7 0 = if _003_ ≠ 0#1 then in_data.extractLsb 7 0 else in_data.extractLsb 15 8)
    : bsort.to_list out_data = layer1 (bsort.to_list in_data) := by
      unfold bsort.to_list layer1;
      rw [ h1, h3, h5, h7, h11, h9, h13, h15 ];
      rw [ h0, h2, h4, h6, h8, h10, h12, h14 ];
      unfold CAS;
      rw [ bitvec_ite_ofBool_ne_zero, bitvec_ite_ofBool_ne_zero, bitvec_ite_ofBool_ne_zero, bitvec_ite_ofBool_ne_zero ];
      rw [ bitvec_ite_ofBool_ne_zero, bitvec_ite_ofBool_ne_zero, bitvec_ite_ofBool_ne_zero, bitvec_ite_ofBool_ne_zero ];
      grind

lemma layer2_correct (in_data out_data : BitVec 64)
    (_004_ _005_ _006_ _007_ _008_ _009_ _010_ _012_ : BitVec 1)
    (h0 : _004_ = BitVec.ofBool (in_data.extractLsb 63 56 ≤ in_data.extractLsb 47 40))
    (h1 : out_data.extractLsb 63 56 = if _004_ ≠ 0#1 then in_data.extractLsb 63 56 else in_data.extractLsb 47 40)
    (h2 : _005_ = BitVec.ofBool (in_data.extractLsb 63 56 ≤ in_data.extractLsb 47 40))
    (h3 : out_data.extractLsb 47 40 = if _005_ ≠ 0#1 then in_data.extractLsb 47 40 else in_data.extractLsb 63 56)
    (h4 : _006_ = BitVec.ofBool (in_data.extractLsb 55 48 ≤ in_data.extractLsb 39 32))
    (h5 : out_data.extractLsb 55 48 = if _006_ ≠ 0#1 then in_data.extractLsb 55 48 else in_data.extractLsb 39 32)
    (h6 : _007_ = BitVec.ofBool (in_data.extractLsb 55 48 ≤ in_data.extractLsb 39 32))
    (h7 : out_data.extractLsb 39 32 = if _007_ ≠ 0#1 then in_data.extractLsb 39 32 else in_data.extractLsb 55 48)
    (h8 : _008_ = BitVec.ofBool (in_data.extractLsb 31 24 ≥ in_data.extractLsb 15 8))
    (h9 : out_data.extractLsb 31 24 = if _008_ ≠ 0#1 then in_data.extractLsb 31 24 else in_data.extractLsb 15 8)
    (h10 : _009_ = BitVec.ofBool (in_data.extractLsb 31 24 ≥ in_data.extractLsb 15 8))
    (h11 : out_data.extractLsb 15 8 = if _009_ ≠ 0#1 then in_data.extractLsb 15 8 else in_data.extractLsb 31 24)
    (h12 : _010_ = BitVec.ofBool (in_data.extractLsb 23 16 ≥ in_data.extractLsb 7 0))
    (h13 : out_data.extractLsb 23 16 = if _010_ ≠ 0#1 then in_data.extractLsb 23 16 else in_data.extractLsb 7 0)
    (h14 : _012_ = BitVec.ofBool (in_data.extractLsb 23 16 ≥ in_data.extractLsb 7 0))
    (h15 : out_data.extractLsb 7 0 = if _012_ ≠ 0#1 then in_data.extractLsb 7 0 else in_data.extractLsb 23 16)
    : bsort.to_list out_data = layer2 (bsort.to_list in_data) := by
      -- By definition of `bsort.to_list`, we can expand both sides of the equation.
      simp [bsort.to_list];
      simp +decide only [h1, h5, h3, h7, h9, h13, h11, h15];
      simp +decide only [h0, h4, h2, h6, h8, h12, h10, h14];
      simp +decide only [bitvec_ite_ofBool_ne_zero];
      unfold layer2;
      unfold CAS;
      grind

lemma layer3_correct (in_data out_data : BitVec 64)
    (_013_ _014_ _015_ _016_ _017_ _018_ _019_ _020_ : BitVec 1)
    (h0 : _013_ = BitVec.ofBool (in_data.extractLsb 63 56 ≤ in_data.extractLsb 55 48))
    (h1 : out_data.extractLsb 63 56 = if _013_ ≠ 0#1 then in_data.extractLsb 63 56 else in_data.extractLsb 55 48)
    (h2 : _014_ = BitVec.ofBool (in_data.extractLsb 63 56 ≤ in_data.extractLsb 55 48))
    (h3 : out_data.extractLsb 55 48 = if _014_ ≠ 0#1 then in_data.extractLsb 55 48 else in_data.extractLsb 63 56)
    (h4 : _015_ = BitVec.ofBool (in_data.extractLsb 47 40 ≤ in_data.extractLsb 39 32))
    (h5 : out_data.extractLsb 47 40 = if _015_ ≠ 0#1 then in_data.extractLsb 47 40 else in_data.extractLsb 39 32)
    (h6 : _016_ = BitVec.ofBool (in_data.extractLsb 47 40 ≤ in_data.extractLsb 39 32))
    (h7 : out_data.extractLsb 39 32 = if _016_ ≠ 0#1 then in_data.extractLsb 39 32 else in_data.extractLsb 47 40)
    (h8 : _017_ = BitVec.ofBool (in_data.extractLsb 31 24 ≥ in_data.extractLsb 23 16))
    (h9 : out_data.extractLsb 31 24 = if _017_ ≠ 0#1 then in_data.extractLsb 31 24 else in_data.extractLsb 23 16)
    (h10 : _018_ = BitVec.ofBool (in_data.extractLsb 31 24 ≥ in_data.extractLsb 23 16))
    (h11 : out_data.extractLsb 23 16 = if _018_ ≠ 0#1 then in_data.extractLsb 23 16 else in_data.extractLsb 31 24)
    (h12 : _019_ = BitVec.ofBool (in_data.extractLsb 15 8 ≥ in_data.extractLsb 7 0))
    (h13 : out_data.extractLsb 15 8 = if _019_ ≠ 0#1 then in_data.extractLsb 15 8 else in_data.extractLsb 7 0)
    (h14 : _020_ = BitVec.ofBool (in_data.extractLsb 15 8 ≥ in_data.extractLsb 7 0))
    (h15 : out_data.extractLsb 7 0 = if _020_ ≠ 0#1 then in_data.extractLsb 7 0 else in_data.extractLsb 15 8)
    : bsort.to_list out_data = layer3 (bsort.to_list in_data) := by
      unfold bsort.to_list layer3;
      rw [ h1, h3, h5, h7, h9, h11, h13, h15 ];
      rw [ h0, h2, h4, h6, h8, h10, h12, h14 ];
      unfold CAS;
      rw [ bitvec_ite_ofBool_ne_zero ];
      rw [ bitvec_ite_ofBool_ne_zero, bitvec_ite_ofBool_ne_zero, bitvec_ite_ofBool_ne_zero, bitvec_ite_ofBool_ne_zero ];
      rw [ bitvec_ite_ofBool_ne_zero ];
      rw [ bitvec_ite_ofBool_ne_zero ];
      rw [ bitvec_ite_ofBool_ne_zero ];
      grind

/-
Helper lemma: `if BitVec.ofBool c = 0 then t else f` is equivalent to `if c then f else t`.
-/
lemma bitvec_ite_ofBool_eq_zero {w : Nat} (c : Prop) [Decidable c] (t f : BitVec w) :
  (if BitVec.ofBool c = 0#1 then t else f) = if c then f else t := by
  split_ifs <;> simp_all

/-
Correctness lemmas for layers 4, 5, and 6 of the Batcher sorter.
-/
lemma layer4_correct (in_data out_data : BitVec 64)
    (_021_ _023_ _024_ _025_ _026_ _027_ _028_ _029_ : BitVec 1)
    (h0 : _021_ = BitVec.ofBool (in_data.extractLsb 63 56 ≤ in_data.extractLsb 31 24))
    (h1 : out_data.extractLsb 63 56 = if _021_ ≠ 0#1 then in_data.extractLsb 63 56 else in_data.extractLsb 31 24)
    (h2 : _023_ = BitVec.ofBool (in_data.extractLsb 63 56 ≤ in_data.extractLsb 31 24))
    (h3 : out_data.extractLsb 31 24 = if _023_ ≠ 0#1 then in_data.extractLsb 31 24 else in_data.extractLsb 63 56)
    (h4 : _024_ = BitVec.ofBool (in_data.extractLsb 55 48 ≤ in_data.extractLsb 23 16))
    (h5 : out_data.extractLsb 55 48 = if _024_ ≠ 0#1 then in_data.extractLsb 55 48 else in_data.extractLsb 23 16)
    (h6 : _025_ = BitVec.ofBool (in_data.extractLsb 55 48 ≤ in_data.extractLsb 23 16))
    (h7 : out_data.extractLsb 23 16 = if _025_ ≠ 0#1 then in_data.extractLsb 23 16 else in_data.extractLsb 55 48)
    (h8 : _026_ = BitVec.ofBool (in_data.extractLsb 47 40 ≤ in_data.extractLsb 15 8))
    (h9 : out_data.extractLsb 47 40 = if _026_ ≠ 0#1 then in_data.extractLsb 47 40 else in_data.extractLsb 15 8)
    (h10 : _027_ = BitVec.ofBool (in_data.extractLsb 47 40 ≤ in_data.extractLsb 15 8))
    (h11 : out_data.extractLsb 15 8 = if _027_ ≠ 0#1 then in_data.extractLsb 15 8 else in_data.extractLsb 47 40)
    (h12 : _028_ = BitVec.ofBool (in_data.extractLsb 39 32 ≤ in_data.extractLsb 7 0))
    (h13 : out_data.extractLsb 39 32 = if _028_ ≠ 0#1 then in_data.extractLsb 39 32 else in_data.extractLsb 7 0)
    (h14 : _029_ = BitVec.ofBool (in_data.extractLsb 39 32 ≤ in_data.extractLsb 7 0))
    (h15 : out_data.extractLsb 7 0 = if _029_ ≠ 0#1 then in_data.extractLsb 7 0 else in_data.extractLsb 39 32)
    : bsort.to_list out_data = layer4 (bsort.to_list in_data) := by
      unfold layer4;
      rcases x : bsort.to_list in_data with _ | ⟨ x0, _ | ⟨ x1, _ | ⟨ x2, _ | ⟨ x3, _ | ⟨ x4, _ | ⟨ x5, _ | ⟨ x6, _ | ⟨ x7, _ | x ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ <;> simp_all +decide;
      all_goals simp_all +decide [ bsort.to_list ];
      unfold CAS; simp +decide [ *, bitvec_ite_ofBool_eq_zero ] ;
      split_ifs <;> simp +decide [ * ]

lemma layer5_correct (in_data out_data : BitVec 64)
    (_030_ _031_ _032_ _034_ _035_ _036_ _037_ _038_ : BitVec 1)
    (h0 : _030_ = BitVec.ofBool (in_data.extractLsb 63 56 ≤ in_data.extractLsb 47 40))
    (h1 : out_data.extractLsb 63 56 = if _030_ ≠ 0#1 then in_data.extractLsb 63 56 else in_data.extractLsb 47 40)
    (h2 : _031_ = BitVec.ofBool (in_data.extractLsb 63 56 ≤ in_data.extractLsb 47 40))
    (h3 : out_data.extractLsb 47 40 = if _031_ ≠ 0#1 then in_data.extractLsb 47 40 else in_data.extractLsb 63 56)
    (h4 : _032_ = BitVec.ofBool (in_data.extractLsb 55 48 ≤ in_data.extractLsb 39 32))
    (h5 : out_data.extractLsb 55 48 = if _032_ ≠ 0#1 then in_data.extractLsb 55 48 else in_data.extractLsb 39 32)
    (h6 : _034_ = BitVec.ofBool (in_data.extractLsb 55 48 ≤ in_data.extractLsb 39 32))
    (h7 : out_data.extractLsb 39 32 = if _034_ ≠ 0#1 then in_data.extractLsb 39 32 else in_data.extractLsb 55 48)
    (h8 : _035_ = BitVec.ofBool (in_data.extractLsb 31 24 ≤ in_data.extractLsb 15 8))
    (h9 : out_data.extractLsb 31 24 = if _035_ ≠ 0#1 then in_data.extractLsb 31 24 else in_data.extractLsb 15 8)
    (h10 : _036_ = BitVec.ofBool (in_data.extractLsb 31 24 ≤ in_data.extractLsb 15 8))
    (h11 : out_data.extractLsb 15 8 = if _036_ ≠ 0#1 then in_data.extractLsb 15 8 else in_data.extractLsb 31 24)
    (h12 : _037_ = BitVec.ofBool (in_data.extractLsb 23 16 ≤ in_data.extractLsb 7 0))
    (h13 : out_data.extractLsb 23 16 = if _037_ ≠ 0#1 then in_data.extractLsb 23 16 else in_data.extractLsb 7 0)
    (h14 : _038_ = BitVec.ofBool (in_data.extractLsb 23 16 ≤ in_data.extractLsb 7 0))
    (h15 : out_data.extractLsb 7 0 = if _038_ ≠ 0#1 then in_data.extractLsb 7 0 else in_data.extractLsb 23 16)
    : bsort.to_list out_data = layer5 (bsort.to_list in_data) := by
      unfold bsort.to_list;
      rw [ layer5 ];
      unfold CAS;
      split_ifs <;> simp +decide [ * ] at *

lemma layer6_correct (in_data out_data : BitVec 64)
    (_039_ _040_ _041_ _042_ _043_ _045_ _046_ _047_ : BitVec 1)
    (h0 : _039_ = BitVec.ofBool (in_data.extractLsb 63 56 ≤ in_data.extractLsb 55 48))
    (h1 : out_data.extractLsb 63 56 = if _039_ ≠ 0#1 then in_data.extractLsb 63 56 else in_data.extractLsb 55 48)
    (h2 : _040_ = BitVec.ofBool (in_data.extractLsb 63 56 ≤ in_data.extractLsb 55 48))
    (h3 : out_data.extractLsb 55 48 = if _040_ ≠ 0#1 then in_data.extractLsb 55 48 else in_data.extractLsb 63 56)
    (h4 : _041_ = BitVec.ofBool (in_data.extractLsb 47 40 ≤ in_data.extractLsb 39 32))
    (h5 : out_data.extractLsb 47 40 = if _041_ ≠ 0#1 then in_data.extractLsb 47 40 else in_data.extractLsb 39 32)
    (h6 : _042_ = BitVec.ofBool (in_data.extractLsb 47 40 ≤ in_data.extractLsb 39 32))
    (h7 : out_data.extractLsb 39 32 = if _042_ ≠ 0#1 then in_data.extractLsb 39 32 else in_data.extractLsb 47 40)
    (h8 : _043_ = BitVec.ofBool (in_data.extractLsb 31 24 ≤ in_data.extractLsb 23 16))
    (h9 : out_data.extractLsb 31 24 = if _043_ ≠ 0#1 then in_data.extractLsb 31 24 else in_data.extractLsb 23 16)
    (h10 : _045_ = BitVec.ofBool (in_data.extractLsb 31 24 ≤ in_data.extractLsb 23 16))
    (h11 : out_data.extractLsb 23 16 = if _045_ ≠ 0#1 then in_data.extractLsb 23 16 else in_data.extractLsb 31 24)
    (h12 : _046_ = BitVec.ofBool (in_data.extractLsb 15 8 ≤ in_data.extractLsb 7 0))
    (h13 : out_data.extractLsb 15 8 = if _046_ ≠ 0#1 then in_data.extractLsb 15 8 else in_data.extractLsb 7 0)
    (h14 : _047_ = BitVec.ofBool (in_data.extractLsb 15 8 ≤ in_data.extractLsb 7 0))
    (h15 : out_data.extractLsb 7 0 = if _047_ ≠ 0#1 then in_data.extractLsb 7 0 else in_data.extractLsb 15 8)
    : bsort.to_list out_data = layer6 (bsort.to_list in_data) := by
      -- By combining the hypotheses, we can show that each step of the layer6 function is correctly applied to the corresponding pairs of elements in the list.
      have h_layer6 : ∀ (x0 x1 x2 x3 x4 x5 x6 x7 : BitVec 8), layer6 [x0, x1, x2, x3, x4, x5, x6, x7] = [if x0 ≤ x1 then x0 else x1, if x0 ≤ x1 then x1 else x0, if x2 ≤ x3 then x2 else x3, if x2 ≤ x3 then x3 else x2, if x4 ≤ x5 then x4 else x5, if x4 ≤ x5 then x5 else x4, if x6 ≤ x7 then x6 else x7, if x6 ≤ x7 then x7 else x6] := by
        intros x0 x1 x2 x3 x4 x5 x6 x7
        simp [layer6, CAS_eq_if];
        split_ifs <;> simp +decide;
      unfold bsort.to_list;
      simp +decide [ *, bitvec_ite_ofBool_eq_zero ]

/-
The bsort circuit implements the Batcher network. Proof using layer correctness lemmas.
-/
theorem bsort_implements_network (input : bsort.Input) (state : bsort.State) (output : bsort.Output) (new_state : bsort.State) :
  bsort.relationalModule.relation input state output new_state →
  bsort.to_list output.out_data = batcher_network (bsort.to_list input.in_data) := by
  intro h
  obtain ⟨_000_, _001_, _002_, _003_, _004_, _005_, _006_, _007_, _008_, _009_, _010_, _011_, _012_, _013_, _014_, _015_, _016_, _017_, _018_, _019_, _020_, _021_, _022_, _023_, _024_, _025_, _026_, _027_, _028_, _029_, _030_, _031_, _032_, _033_, _034_, _035_, _036_, _037_, _038_, _039_, _040_, _041_, _042_, _043_, _044_, _045_, _046_, _047_, phase0_sub0, phase1_sub0, phase1_sub1, phase2_sub0, phase2_sub1, phase2_sub2, h_eqs, h_state⟩ := h
  simp only [List.PropAnd_cons, List.PropAnd_nil] at h_eqs

  have h_l1 : bsort.to_list phase0_sub0 = layer1 (bsort.to_list input.in_data) := by
    apply layer1_correct input.in_data phase0_sub0 _000_ _001_ _002_ _003_ _011_ _022_ _033_ _044_
    all_goals (try simp [h_eqs])

  have h_l2 : bsort.to_list phase1_sub1 = layer2 (bsort.to_list phase0_sub0) := by
    apply layer2_correct phase0_sub0 phase1_sub1 _004_ _005_ _006_ _007_ _008_ _009_ _010_ _012_
    all_goals (try simp [h_eqs])

  have h_l3 : bsort.to_list phase1_sub0 = layer3 (bsort.to_list phase1_sub1) := by
    apply layer3_correct phase1_sub1 phase1_sub0 _013_ _014_ _015_ _016_ _017_ _018_ _019_ _020_
    all_goals (try simp [h_eqs])

  have h_l4 : bsort.to_list phase2_sub2 = layer4 (bsort.to_list phase1_sub0) := by
    apply layer4_correct phase1_sub0 phase2_sub2 _021_ _023_ _024_ _025_ _026_ _027_ _028_ _029_
    all_goals (try simp [h_eqs])

  have h_l5 : bsort.to_list phase2_sub1 = layer5 (bsort.to_list phase2_sub2) := by
    apply layer5_correct phase2_sub2 phase2_sub1 _030_ _031_ _032_ _034_ _035_ _036_ _037_ _038_
    all_goals (try simp [h_eqs])

  have h_l6 : bsort.to_list output.out_data = layer6 (bsort.to_list phase2_sub1) := by
    apply layer6_correct phase2_sub1 output.out_data _039_ _040_ _041_ _042_ _043_ _045_ _046_ _047_
    all_goals (try simp [h_eqs])

  rw [h_l6, h_l5, h_l4, h_l3, h_l2, h_l1]
  rfl

/-
CAS returns a permutation of its input.
-/
lemma CAS_perm (asc : Bool) (a b : BitVec 8) :
  [(CAS asc a b).1, (CAS asc a b).2].Perm [a, b] := by
    cases asc <;> simp +decide [ CAS ];
    · split_ifs <;> simp +decide [ *, List.Perm.swap ];
    · split_ifs <;> simp +decide [ *, List.Perm.swap ]

/-
Layer 1 preserves permutation.
-/
lemma layer1_perm (l : List (BitVec 8)) : (layer1 l).Perm l := by
  rcases l with ( _ | ⟨ x0, _ | ⟨ x1, _ | ⟨ x2, _ | ⟨ x3, _ | ⟨ x4, _ | ⟨ x5, _ | ⟨ x6, _ | ⟨ x7, _ | l ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ) <;> simp +decide [ layer1 ];
  have h_perm : ∀ (a b : BitVec 8), List.Perm [(CAS true a b).1, (CAS true a b).2] [a, b] ∧ List.Perm [(CAS false a b).1, (CAS false a b).2] [a, b] := by
    exact fun a b => ⟨ CAS_perm true a b, CAS_perm false a b ⟩;
  exact List.Perm.append ( List.Perm.append ( List.Perm.append ( h_perm _ _ |>.1 ) ( h_perm _ _ |>.2 ) ) ( h_perm _ _ |>.1 ) ) ( h_perm _ _ |>.2 )

/-
Layer 2 preserves permutation.
-/
lemma perm_swap_2_3 {α} (a b c d : α) (l : List α) : (a :: b :: c :: d :: l).Perm (a :: c :: b :: d :: l) := by
  constructor;
  constructor

lemma layer2_perm (l : List (BitVec 8)) : (layer2 l).Perm l := by
  unfold layer2;
  rcases l with ( _ | ⟨ x0, _ | ⟨ x1, _ | ⟨ x2, _ | ⟨ x3, _ | ⟨ x4, _ | ⟨ x5, _ | ⟨ x6, _ | ⟨ x7, _ | l ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ) <;> simp +decide [ List.Perm.swap ];
  unfold CAS; simp +decide [ List.Perm.swap ] ;
  split_ifs <;> simp +decide [ *, List.Perm.swap ];
  all_goals rw [ List.perm_iff_count ] ; intros ; simp +decide [ List.count_cons ] ;
  all_goals ring;

/-
Layer 3 preserves permutation.
-/
lemma layer3_perm (l : List (BitVec 8)) : (layer3 l).Perm l := by
  unfold layer3;
  rcases l with ( _ | ⟨ x0, _ | ⟨ x1, _ | ⟨ x2, _ | ⟨ x3, _ | ⟨ x4, _ | ⟨ x5, _ | ⟨ x6, _ | ⟨ x7, _ | l ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ) <;> simp +decide [ List.Perm.swap ];
  unfold CAS; simp +decide [ List.Perm.swap ] ;
  split_ifs <;> simp +decide [ *, List.Perm.swap ];
  all_goals rw [ List.perm_iff_count ] ; intros ; simp +decide [ List.count_cons ] ;
  all_goals ring;

/-
Layer 4 preserves permutation.
-/
lemma layer4_perm (l : List (BitVec 8)) : (layer4 l).Perm l := by
  unfold layer4;
  rcases l with ( _ | ⟨ x0, _ | ⟨ x1, _ | ⟨ x2, _ | ⟨ x3, _ | ⟨ x4, _ | ⟨ x5, _ | ⟨ x6, _ | ⟨ x7, _ | l ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ) <;> simp +decide [ List.Perm.swap ];
  unfold CAS; simp +decide [ List.Perm.swap ] ;
  split_ifs <;> simp +decide [ *, List.Perm.swap ];
  all_goals rw [ List.perm_iff_count ] ; intros ; simp +decide [ List.count_cons ] ;
  all_goals ring;

/-
Layer 5 preserves permutation.
-/
lemma layer5_perm (l : List (BitVec 8)) : (layer5 l).Perm l := by
  unfold layer5;
  rcases l with ( _ | ⟨ x0, _ | ⟨ x1, _ | ⟨ x2, _ | ⟨ x3, _ | ⟨ x4, _ | ⟨ x5, _ | ⟨ x6, _ | ⟨ x7, _ | l ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ) <;> simp +decide [ List.Perm.swap ];
  unfold CAS; simp +decide [ List.Perm.swap ] ;
  split_ifs <;> simp +decide [ *, List.Perm.swap ];
  all_goals rw [ List.perm_iff_count ] ; intros ; simp +decide [ List.count_cons ] ;
  all_goals ring;

/-
Layer 6 preserves permutation.
-/
lemma layer6_perm (l : List (BitVec 8)) : (layer6 l).Perm l := by
  unfold layer6;
  rcases l with ( _ | ⟨ x0, _ | ⟨ x1, _ | ⟨ x2, _ | ⟨ x3, _ | ⟨ x4, _ | ⟨ x5, _ | ⟨ x6, _ | ⟨ x7, _ | l ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ) <;> simp +decide [ List.Perm.swap ];
  unfold CAS; simp +decide [ List.Perm.swap ] ;
  split_ifs <;> simp +decide [ *, List.Perm.swap ];
  all_goals rw [ List.perm_iff_count ] ; intros ; simp +decide [ List.count_cons ] ;
  all_goals ring;

/-
The Batcher network preserves permutation.
-/
theorem batcher_network_perm (l : List (BitVec 8)) : (batcher_network l).Perm l := by
  unfold batcher_network
  apply List.Perm.trans (layer6_perm _)
  apply List.Perm.trans (layer5_perm _)
  apply List.Perm.trans (layer4_perm _)
  apply List.Perm.trans (layer3_perm _)
  apply List.Perm.trans (layer2_perm _)
  apply layer1_perm

/-
Layer 1 establishes the initial bitonic shapes.
-/
def PostLayer1 (l : List (BitVec 8)) : Prop :=
  l.length = 8 ∧
  l[0]! ≤ l[1]! ∧
  l[2]! ≥ l[3]! ∧
  l[4]! ≤ l[5]! ∧
  l[6]! ≥ l[7]!

lemma layer1_establishes_PostLayer1 (l : List (BitVec 8)) (h : l.length = 8) :
  PostLayer1 (layer1 l) := by
    rcases l with ( _ | ⟨ a, _ | ⟨ b, _ | ⟨ c, _ | ⟨ d, _ | ⟨ e, _ | ⟨ f, _ | ⟨ g, _ | ⟨ h, _ | l ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ) <;> simp_all +decide;
    constructor;
    · simp +decide [ layer1 ];
    · unfold layer1;
      unfold CAS; simp +decide [ * ] ;
      grind

/-
Layer 2 establishes the second stage bitonic properties.
-/
def PostLayer2 (l : List (BitVec 8)) : Prop :=
  l.length = 8 ∧
  l[0]! ≤ l[2]! ∧
  l[1]! ≤ l[3]! ∧
  l[0]! ≤ l[3]! ∧
  l[1]! ≤ l[2]! ∧
  l[4]! ≥ l[6]! ∧
  l[5]! ≥ l[7]! ∧
  l[4]! ≥ l[7]! ∧
  l[5]! ≥ l[6]!

lemma layer2_establishes_PostLayer2 (l : List (BitVec 8)) (h : PostLayer1 l) :
  PostLayer2 (layer2 l) := by
    unfold PostLayer1 at h; unfold layer2; simp_all? ( config := { decide := Bool.true } ) ;
    rcases l with ( _ | ⟨ x0, _ | ⟨ x1, _ | ⟨ x2, _ | ⟨ x3, _ | ⟨ x4, _ | ⟨ x5, _ | ⟨ x6, _ | ⟨ x7, _ | l ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ) <;> simp_all +decide;
    unfold PostLayer2; simp +decide [ CAS ] ;
    split_ifs <;> simp_all +decide [ BitVec.le_def ];
    all_goals omega;

/-
Layer 3 establishes that the first half is sorted ascending and the second half is sorted descending.
-/
def PostLayer3 (l : List (BitVec 8)) : Prop :=
  l.length = 8 ∧
  l[0]! ≤ l[1]! ∧ l[1]! ≤ l[2]! ∧ l[2]! ≤ l[3]! ∧
  l[4]! ≥ l[5]! ∧ l[5]! ≥ l[6]! ∧ l[6]! ≥ l[7]!

lemma layer3_establishes_PostLayer3 (l : List (BitVec 8)) (h : PostLayer2 l) :
  PostLayer3 (layer3 l) := by
    rcases l with ( _ | ⟨ a, _ | ⟨ b, _ | ⟨ c, _ | ⟨ d, _ | ⟨ e, _ | ⟨ f, _ | ⟨ g, _ | ⟨ h, _ | l ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ) <;> simp_all? +arith +decide [ PostLayer2, PostLayer3 ];
    unfold layer3; simp +decide [ CAS ] ;
    grind

/-
Definition of `sort4` and `IsBitonic4`. `sort4` corresponds to layers 5 and 6 for a 4-element chunk. `IsBitonic4` characterizes bitonic sequences of length 4.
-/
def sort4 (l : List (BitVec 8)) : List (BitVec 8) :=
  match l with
  | x0 :: x1 :: x2 :: x3 :: [] =>
    let (y0, y2) := CAS true x0 x2
    let (y1, y3) := CAS true x1 x3
    let (z0, z1) := CAS true y0 y1
    let (z2, z3) := CAS true y2 y3
    [z0, z1, z2, z3]
  | _ => l

def IsBitonic4 (l : List (BitVec 8)) : Prop :=
  l.length = 4 ∧
  let x0 := l[0]!
  let x1 := l[1]!
  let x2 := l[2]!
  let x3 := l[3]!
  ¬(x0 < x1 ∧ x1 > x2 ∧ x2 < x3 ∧ x3 > x0) ∧
  ¬(x0 > x1 ∧ x1 < x2 ∧ x2 > x3 ∧ x3 < x0)

/-
Definitions of Up-Then-Down and Down-Then-Up sequences of length 4.
-/
def IsUpThenDown4 (l : List (BitVec 8)) : Prop :=
  l.length = 4 ∧
  ∃ (k : Fin 5),
    (∀ i j, i < j → j < k → l[i]! ≤ l[j]!) ∧
    (∀ i j, k ≤ i → i < j → j < 4 → l[i]! ≥ l[j]!)

def IsDownThenUp4 (l : List (BitVec 8)) : Prop :=
  l.length = 4 ∧
  ∃ (k : Fin 5),
    (∀ i j, i < j → j < k → l[i]! ≥ l[j]!) ∧
    (∀ i j, k ≤ i → i < j → j < 4 → l[i]! ≤ l[j]!)

/-
`sort4` sorts any bitonic sequence of length 4. Proof uses `omega` on `toNat` values.
-/
lemma sort4_sorts_bitonic (l : List (BitVec 8)) (h_len : l.length = 4) (h_bitonic : IsBitonic4 l) :
  List.Sorted (· ≤ ·) (sort4 l) := by
    unfold sort4;
    rcases l with ( _ | ⟨ x0, _ | ⟨ x1, _ | ⟨ x2, _ | ⟨ x3, _ | l ⟩ ⟩ ⟩ ⟩ ) <;> simp_all +decide;
    unfold CAS; split_ifs <;> simp_all +decide ;
    all_goals unfold IsBitonic4 at h_bitonic; simp_all +decide [ not_lt_of_ge, le_of_lt ] ;
    all_goals simp_all +decide [ BitVec.le_def, BitVec.lt_def ];
    all_goals omega

/-
`sort4` sorts Up-Then-Down sequences.
-/
lemma sort4_sorts_UpThenDown (l : List (BitVec 8)) (h : IsUpThenDown4 l) :
  List.Sorted (· ≤ ·) (sort4 l) := by
    rcases h with ⟨ h_len, k, hk ⟩;
    -- We need to show that `sort4 l` is sorted for any `l` that is up-then-down.
    apply sort4_sorts_bitonic;
    · assumption;
    · fin_cases k <;> simp +decide [ Fin.forall_fin_succ ] at hk ⊢;
      · constructor <;> aesop;
      · unfold IsBitonic4; aesop;
      · constructor <;> aesop;
      · constructor <;> aesop;
      · exact ⟨ h_len, by aesop ⟩

/-
`sort4` sorts Down-Then-Up sequences.
-/
lemma sort4_sorts_DownThenUp (l : List (BitVec 8)) (h : IsDownThenUp4 l) :
  List.Sorted (· ≤ ·) (sort4 l) := by
    obtain ⟨ k, hk ⟩ := h;
    rcases l with ( _ | ⟨ a, _ | ⟨ b, _ | ⟨ c, _ | ⟨ d, _ | l ⟩ ⟩ ⟩ ⟩ ) <;> simp_all +decide;
    revert hk;
    simp +decide [ Fin.forall_fin_succ, Fin.exists_fin_succ ];
    unfold sort4; simp +decide [ List.Sorted ] ;
    unfold CAS; simp +decide [ *, le_total ] ;
    grind

/-
`layer6 (layer5 l)` is equivalent to applying `sort4` to the two halves of `l`.
-/
lemma layer56_eq_sort4_halves (l : List (BitVec 8)) (h : l.length = 8) :
  layer6 (layer5 l) = sort4 (l.take 4) ++ sort4 (l.drop 4) := by
  rcases l with ( _ | ⟨ x0, _ | ⟨ x1, _ | ⟨ x2, _ | ⟨ x3, _ | ⟨ x4, _ | ⟨ x5, _ | ⟨ x6, _ | ⟨ x7, _ | l ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ) <;> simp_all
  unfold layer6 layer5 sort4
  simp

/-
`layer4` partitions the sequence into a lower half and an upper half such that every element in the lower half is less than or equal to every element in the upper half.
-/
lemma layer4_partition (l : List (BitVec 8)) (h : PostLayer3 l) :
  let l' := layer4 l
  ∀ x ∈ l'.take 4, ∀ y ∈ l'.drop 4, x ≤ y := by
    rcases l with ( _ | ⟨ x0, _ | ⟨ x1, _ | ⟨ x2, _ | ⟨ x3, _ | ⟨ x4, _ | ⟨ x5, _ | ⟨ x6, _ | ⟨ x7, _ | l ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ) <;> simp_all +decide;
    all_goals unfold PostLayer3 at h; simp_all +decide;
    unfold layer4; simp +decide [ CAS ] ;
    split_ifs <;> simp_all +decide [ BitVec.le_def ];
    all_goals omega;

/-
`IsUpThenDown4` implies `IsBitonic4`.
-/
lemma IsUpThenDown4_implies_IsBitonic4 (l : List (BitVec 8)) (h : IsUpThenDown4 l) : IsBitonic4 l := by
  rcases h with ⟨h_len, k, h_asc, h_desc⟩
  unfold IsBitonic4
  simp [h_len]
  fin_cases k
  all_goals {
    simp only [Fin.forall_fin_succ, Fin.forall_fin_zero_pi] at h_asc h_desc
    simp_all
    -- In each case, we have some inequalities.
    -- We need to show negation of M and W.
    -- M: x0 < x1 > x2 < x3 > x0
    -- W: x0 > x1 < x2 > x3 < x0
    -- Use `bv_decide` or `omega` if possible, or just logic.
    -- Since we have `BitVec`, `omega` works on `toNat`.
    try simp only [← BitVec.toNat_le, ← BitVec.toNat_lt] at *
    try omega
  }

/-
`IsDownThenUp4` implies `IsBitonic4`.
-/
lemma IsDownThenUp4_implies_IsBitonic4 (l : List (BitVec 8)) (h : IsDownThenUp4 l) : IsBitonic4 l := by
  rcases h with ⟨h_len, k, h_desc, h_asc⟩
  unfold IsBitonic4
  simp [h_len]
  fin_cases k
  all_goals {
    simp only [Fin.forall_fin_succ, Fin.forall_fin_zero_pi] at h_asc h_desc
    simp_all
    try simp only [← BitVec.toNat_le, ← BitVec.toNat_lt] at *
    try omega
  }

/-
If the input to `layer4` consists of an ascending half and a descending half, then the two halves of the output of `layer4` are bitonic.
-/
lemma layer4_halves_bitonic (l : List (BitVec 8)) (h : PostLayer3 l) :
  IsBitonic4 ((layer4 l).take 4) ∧ IsBitonic4 ((layer4 l).drop 4) := by
    unfold IsBitonic4 PostLayer3 at *;
    rcases l with ( _ | ⟨ a, _ | ⟨ b, _ | ⟨ c, _ | ⟨ d, _ | ⟨ e, _ | ⟨ f, _ | ⟨ g, _ | ⟨ h, _ | l ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ) <;> simp_all +decide [ layer4 ];
    unfold CAS; simp +decide [ h ] ;
    grind

/-
`sort4` returns a permutation of its input.
-/
lemma sort4_perm (l : List (BitVec 8)) : (sort4 l).Perm l := by
  unfold sort4;
  rcases l with ( _ | ⟨ x0, _ | ⟨ x1, _ | ⟨ x2, _ | ⟨ x3, _ | l ⟩ ⟩ ⟩ ⟩ ) <;> simp +decide [ CAS ];
  grind

/-
Helper lemma: Concatenation of two sorted lists where the first is less than or equal to the second is sorted.
-/
lemma List.Sorted.append_of_le {α} [Preorder α] {l1 l2 : List α}
  (h1 : List.Sorted (· ≤ ·) l1) (h2 : List.Sorted (· ≤ ·) l2)
  (hle : ∀ x ∈ l1, ∀ y ∈ l2, x ≤ y) :
  List.Sorted (· ≤ ·) (l1 ++ l2) := by
    induction l1 <;> aesop

/-
Layers 4, 5, and 6 sort a sequence that satisfies PostLayer3. Proof uses the decomposition into `sort4` on halves and the partition property of `layer4`.
-/
lemma layer456_sorts (l : List (BitVec 8)) (h : PostLayer3 l) :
  List.Sorted (· ≤ ·) (layer6 (layer5 (layer4 l))) := by
    -- By lemma `layer4_partition`, the first half of `layer4 l` is less than or equal to the second half.
    have h_partition : ∀ x ∈ (layer4 l).take 4, ∀ y ∈ (layer4 l).drop 4, x ≤ y := by
      apply layer4_partition; assumption;
    -- By lemma `layer56_eq_sort4_halves`, `layer6 (layer5 l)` is equivalent to applying `sort4` to the two halves of `l`.
    have h_sort4 : layer6 (layer5 (layer4 l)) = sort4 ((layer4 l).take 4) ++ sort4 ((layer4 l).drop 4) := by
      convert layer56_eq_sort4_halves ( layer4 l ) _;
      rcases l with ( _ | ⟨ a, _ | ⟨ b, _ | ⟨ c, _ | ⟨ d, _ | ⟨ e, _ | ⟨ f, _ | ⟨ g, _ | ⟨ h, _ | l ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ⟩ ) <;> simp_all +decide [ layer4 ];
      all_goals cases h; simp_all +decide [ PostLayer3 ] ;
    -- By lemma `sort4_sorts_bitonic`, `sort4` sorts bitonic sequences.
    have h_sort4_bitonic : List.Sorted (· ≤ ·) (sort4 ((layer4 l).take 4)) ∧ List.Sorted (· ≤ ·) (sort4 ((layer4 l).drop 4)) := by
      have h_sort4_bitonic : IsBitonic4 ((layer4 l).take 4) ∧ IsBitonic4 ((layer4 l).drop 4) := by
        exact?;
      exact ⟨ sort4_sorts_bitonic _ ( by simp +decide [ h_sort4_bitonic.1.1 ] ) h_sort4_bitonic.1, sort4_sorts_bitonic _ ( by simp +decide [ h_sort4_bitonic.2.1 ] ) h_sort4_bitonic.2 ⟩;
    -- By lemma `List.Sorted.append_of_le`, the concatenation of two sorted lists where the first is less than or equal to the second is sorted.
    have h_concat_sorted : ∀ {l1 l2 : List (BitVec 8)}, List.Sorted (· ≤ ·) l1 → List.Sorted (· ≤ ·) l2 → (∀ x ∈ l1, ∀ y ∈ l2, x ≤ y) → List.Sorted (· ≤ ·) (l1 ++ l2) := by
      intros l1 l2 hl1 hl2 hle; exact (by
      rw [ List.Sorted ] at *;
      rw [ List.pairwise_append ] ; aesop);
    contrapose! h_concat_sorted;
    use sort4 ((layer4 l).take 4), sort4 ((layer4 l).drop 4);
    simp_all +decide [ List.Sorted ];
    intro x hx y hy; have := List.Perm.subset ( sort4_perm ( List.take 4 ( layer4 l ) ) ) hx; have := List.Perm.subset ( sort4_perm ( List.drop 4 ( layer4 l ) ) ) hy; aesop;

/-
Final proof of correctness for the bsort module.
-/
theorem bsort_correct (input : bsort.Input) (state : bsort.State) (output : bsort.Output) (new_state : bsort.State) :
  bsort.relationalModule.relation input state output new_state →
  let in_list := bsort.to_list input.in_data
  let out_list := bsort.to_list output.out_data
  List.Sorted (· ≤ ·) out_list ∧ List.Perm in_list out_list := by
    -- Apply the lemma that states the Batcher network sorts the input.
    intro h_relational
    have h_sorted : List.Sorted (· ≤ ·) (bsort.to_list output.out_data) := by
      rw [ bsort_implements_network input state output new_state h_relational ];
      apply layer456_sorts;
      apply_rules [ layer3_establishes_PostLayer3, layer2_establishes_PostLayer2, layer1_establishes_PostLayer1 ];
    have := bsort_implements_network input state output new_state h_relational;
    exact ⟨ h_sorted, this ▸ batcher_network_perm _ |> List.Perm.symm ⟩

/-
Layers 4, 5, and 6 sort a sequence that satisfies PostLayer3. Proof uses the decomposition into `sort4` on halves and the partition property of `layer4`.
-/
lemma layer456_sorts_final (l : List (BitVec 8)) (h : PostLayer3 l) :
  List.Sorted (· ≤ ·) (layer6 (layer5 (layer4 l))) := by
    exact?

/-
Final proof of correctness for the bsort module (renamed to avoid conflict).
-/
theorem bsort_correctness (input : bsort.Input) (state : bsort.State) (output : bsort.Output) (new_state : bsort.State) :
  bsort.relationalModule.relation input state output new_state →
  let in_list := bsort.to_list input.in_data
  let out_list := bsort.to_list output.out_data
  List.Sorted (· ≤ ·) out_list ∧ List.Perm in_list out_list := by
    -- Apply the lemma `bsort_correct` to conclude the proof.
    apply bsort_correct
